export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Harsh Panchal",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Poojan Makwana",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Jemisha Patel",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Dwiti Pandya",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Kuldip Matroja",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Yash Gor",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Dhruv Varia",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Dev Thakkar",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Yuvraj Baria",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Parth Panchal",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 320,
    comment: 90,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 20,
    comment: 10,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 610,
    comment: 20,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 70,
    comment: 30,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 230,
    comment: 50,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 440,
    comment: 60,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 520,
    comment: 30,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 150,
    comment: 10,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 110,
    comment: 20,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
